@startuml
namespace parser {
    class Struct << (S,Aquamarine) >> {
        + PackageName string
        + Functions []*Function
        + Fields []*Field
        + Type string
        + Composition <font color=blue>map</font>[string]<font color=blue>struct</font>{}
        + Extends <font color=blue>map</font>[string]<font color=blue>struct</font>{}
        + Aggregations <font color=blue>map</font>[string]<font color=blue>struct</font>{}

        + ImplementsInterface(inter *Struct) bool
        + AddToComposition(fType string) 
        + AddToExtends(fType string) 
        + AddToAggregation(fType string) 
        + AddField(field *ast.Field, aliases <font color=blue>map</font>[string]string) 
        + AddMethod(method *ast.Field, aliases <font color=blue>map</font>[string]string) 

    }
    class Function << (S,Aquamarine) >> {
        + Name string
        + Parameters []*Field
        + ReturnValues []string
        + PackageName string
        + FullNameReturnValues []string

        + SignturesAreEqual(function *Function) bool

    }
    class Alias << (S,Aquamarine) >> {
        + Name string
        + PackageName string
        + AliasOf string

    }
    class Field << (S,Aquamarine) >> {
        + Name string
        + Type string
        + FullType string

    }
    class LineStringBuilder << (S,Aquamarine) >> {
        + WriteLineWithDepth(depth int, str string) 

    }
    class RenderingOptions << (S,Aquamarine) >> {
        + Aggregation bool

    }
    class ClassParser << (S,Aquamarine) >> {
        - renderingOptions *RenderingOptions
        - structure <font color=blue>map</font>[string]<font color=blue>map</font>[string]*Struct
        - currentPackageName string
        - allInterfaces <font color=blue>map</font>[string]<font color=blue>struct</font>{}
        - allStructs <font color=blue>map</font>[string]<font color=blue>struct</font>{}
        - allImports <font color=blue>map</font>[string]string
        - allAliases <font color=blue>map</font>[string]*Alias

        - parsePackage(node ast.Node) 
        - parseImports(impt *ast.ImportSpec) 
        - parseDirectory(directoryPath string) error
        - parseFileDeclarations(node ast.Decl) 
        - handleFuncDecl(decl *ast.FuncDecl) 
        - handleGenDecl(decl *ast.GenDecl) 
        - renderStructures(pack string, structures <font color=blue>map</font>[string]*Struct, str *LineStringBuilder) 
        - renderStructure(structure *Struct, pack string, name string, str *LineStringBuilder, composition *LineStringBuilder, extends *LineStringBuilder, aggregations *LineStringBuilder) 
        - renderCompositions(structure *Struct, name string, composition *LineStringBuilder) 
        - renderAggregations(structure *Struct, name string, aggregations *LineStringBuilder) 
        - getPackageName(t string, st *Struct) string
        - renderExtends(structure *Struct, name string, extends *LineStringBuilder) 
        - renderStructMethods(structure *Struct, privateMethods *LineStringBuilder, publicMethods *LineStringBuilder) 
        - renderStructFields(structure *Struct, privateFields *LineStringBuilder, publicFields *LineStringBuilder) 
        - getOrCreateStruct(name string) *Struct
        - getStruct(structName string) *Struct

        + Render() string
        + SetRenderingOptions(ro *RenderingOptions) 

    }
}
"strings.Builder" *-- "parser.LineStringBuilder"


"parser.Struct" o-- "parser.Function"
"parser.Struct" o-- "parser.Field"
"parser.Function" o-- "parser.Field"

@enduml
