@startuml
namespace parser {
    class Field {
        + Name string
        + Type string

    }
    class LineStringBuilder {
        + WriteLineWithDepth(depth int, str string) 

    }
    class ClassParser {
        - structure <font color=blue>map</font>[string]<font color=blue>map</font>[string]*Struct
        - currentPackageName string
        - allInterfaces <font color=blue>map</font>[string]<font color=blue>struct</font>{}
        - allStructs <font color=blue>map</font>[string]<font color=blue>struct</font>{}

        - parsePackage(node ast.Node) 
        - parseFileDeclarations(node ast.Decl) 
        - getOrCreateStruct(name string) 
        - getStruct(structName string) 

        + Render() 

    }
    class Struct {
        + PackageName string
        + Functions []*Function
        + Fields []*Field
        + Type string
        + Composition []string
        + Extends []string

        + ImplementsInterface(inter *Struct) 
        + AddToComposition(fType string) 
        + AddToExtends(fType string) 
        + AddField(field *ast.Field) 
        + AddMethod(method *ast.Field) 

    }
    class Function {
        + Name string
        + Parameters []*Field
        + ReturnValues []string

        + SignturesAreEqual(function *Function) 

    }
}
strings.Builder *-- parser.LineStringBuilder


@enduml