@startuml
    class "Subfolder2" << (S,Aquamarine) >> {
        + SubfolderFunction(b bool, i int) bool
        + SubfolderFunctionWithReturnListParametrized() ([]byte, []byte, []byte, error)

    }
    interface "SubfolderInterface"  {
        + SubfolderFunction( bool,  int) bool

    }

"subfolder3.SubfolderInterface" <|-- "subfolder2.Subfolder2"


@enduml
