@startuml
namespace subfolder2 {
    class Subfolder2 << (S,Aquamarine) >> {
        + SubfolderFunction(b bool, i int) bool
        + SubfolderFunctionWithReturnListParametrized() ([]byte, []byte, []byte, error)

    }
}

"subfolder3.SubfolderInterface" <|-- "subfolder2.Subfolder2"

namespace subfolder3 {
    interface SubfolderInterface  {
        + SubfolderFunction( bool,  int) bool

    }
}


@enduml
