@startuml
namespace testingsupport {
    class test << (S,Aquamarine) >> {
        - field int

        - test() 

    }
    class testingsupport.myInt << (T, #FF7700) >>  {
    }
}


"__builtin__.int" #.. "testingsupport.myInt"
@enduml
