@startuml
namespace testingsupport {
    class testingsupport.myInt << (T, #FF7700) >>  {
    }
    class test << (S,Aquamarine) >> {
        - field int

        - test() 

    }
}


__builtin__.int #.. testingsupport.myInt
@enduml
